lists excercise
tony-sologubov/ru-study-python pull request #1
Opened 2022-12-22 15:01 UTC by tony-sologubov

2022-12-23 11:49 UTC, aleksandr-semenov-dbp requested changes

2022-12-23 11:49 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +        return -1
Алгоритм верный, но по условию требуется сделать это рекурсивно.

2022-12-23 12:29 UTC, tony-sologubov commented on lists/lists.py
> +        return -1
Что-то не найду требование сделать рекурсивно.

2023-01-11 13:03 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +        return -1
![image](https://user-images.githubusercontent.com/99636676/211813290-2d901295-bbf5-4b05-a79a-9ecb00bc8982.png)

2023-01-15 22:29 UTC, aleksandr-semenov-dbp approved these changes

2023-01-16 09:45 UTC, merged